apiVersion: v1
kind: Service
metadata:
  name: nodejs-troubleshoot
spec:
  selector:
    app: nodejs-troubleshoot
    version: 1.0.0
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort